/**
 * Tracking Service — Business logic for tracking codes and history.
 * Handles code generation, approval workflow, validation, public lookup, and event management.
 *
 * Approval Flow:
 * 1. Customer linked to BL → auto-generate code (pending)
 * 2. Admin reviews pending codes → approve or reject
 * 3. On approve → code activated + email/WhatsApp prepared for customer
 * 4. On reject → code deactivated with reason
 */
import * as repo from "./repository";
import * as blRepo from "../bls/repository";
import * as customerRepo from "../customers/repository";
import * as vehicleRepo from "../vehicles/repository";
import { logAudit } from "../../shared/audit";
import { hashCpfForSearch, secureLogger } from "../../shared/security";
import { InMemoryCache } from "../../shared/cache";
import {
  dispatchEventNotifications,
  notifyNewTrackingCode,
  notifyPendingApproval,
  notifyCodeApproved,
} from "./notifications";
import type { PaginatedQuery, PaginatedResult } from "../../shared/pagination";

// ── Cache for public tracking lookups (5 min TTL) ────────────
const trackingCache = new InMemoryCache<PublicTrackingResult>({ ttl: 300 });

// ── Public result types ──────────────────────────────────────
export interface PublicVehicleInfo {
  make: string | null;
  model: string | null;
  year: number | null;
  color: string | null;
}

export interface PublicTrackingResult {
  code: string;
  blNumber: string;
  containerNumber: string | null;
  originPort: string | null;
  destinationPort: string | null;
  vehicleDescription: string | null;
  /** Detailed vehicle info from bl_vehicles (no personal data) */
  vehicles: PublicVehicleInfo[];
  status: string;
  estimatedDeparture: Date | null;
  actualDeparture: Date | null;
  estimatedArrival: Date | null;
  actualArrival: Date | null;
  timeline: Array<{
    status: string;
    location: string | null;
    description: string | null;
    eventDate: Date;
  }>;
  lastUpdate: Date | null;
}

export interface CpfLookupResult {
  codes: Array<{
    codeMasked: string;
    blNumber: string;
    status: string;
    vehicleDescription: string | null;
  }>;
  customerNameMasked: string;
}

// ══════════════════════════════════════════════════════════════
// TRACKING CODES — Generation & Approval
// ══════════════════════════════════════════════════════════════

/**
 * Generate a tracking code for a BL+Customer.
 * Manual generation by admin — starts as "pending" for approval.
 */
export async function generateTrackingCode(
  blId: number,
  customerId: number,
  expiresInDays: number = 365,
  adminUserId?: number
): Promise<repo.TrackingCodeRecord> {
  // Validate BL exists
  const bl = await blRepo.findBlById(blId);
  if (!bl) throw new Error("BL não encontrado.");

  // Validate customer exists
  const customer = await customerRepo.findCustomerById(customerId);
  if (!customer) throw new Error("Cliente não encontrado.");

  // Check for existing pending/approved code
  const existing = await repo.findCodeByBlAndCustomer(blId, customerId);
  if (existing && (existing.approvalStatus === "pending" || existing.approvalStatus === "approved")) {
    throw new Error(
      `Já existe um código ${existing.approvalStatus === "pending" ? "pendente de aprovação" : "ativo"} para este cliente e BL.`
    );
  }

  const code = await repo.createTrackingCode(blId, customerId, {
    expiresInDays,
    autoGenerated: false,
    approvalStatus: "pending",
  });

  await logAudit({
    userId: adminUserId ?? null,
    action: "create",
    entity: "tracking_code",
    entityId: code.id,
    changes: {
      created: { before: null, after: code.code },
      blId: { before: null, after: blId },
      customerId: { before: null, after: customerId },
      approvalStatus: { before: null, after: "pending" },
    },
  });

  // Notify owner about pending code (fire-and-forget)
  notifyPendingApproval({
    blNumber: bl.blNumber,
    trackingCode: code.code,
    customerName: customer.fullName,
    vehicleDescription: bl.vehicleDescription,
    autoGenerated: false,
  }).catch((err) => console.error("[Tracking Service] Pending notification error:", err));

  return code;
}

/**
 * Auto-generate a tracking code when a customer is linked to a BL.
 * Called internally — creates code as "pending" for admin review.
 */
export async function autoGenerateTrackingCode(
  blId: number,
  customerId: number
): Promise<repo.TrackingCodeRecord | null> {
  // Validate BL exists
  const bl = await blRepo.findBlById(blId);
  if (!bl) return null;

  // Validate customer exists
  const customer = await customerRepo.findCustomerById(customerId);
  if (!customer) return null;

  // Check for existing code (avoid duplicates)
  const existing = await repo.findCodeByBlAndCustomer(blId, customerId);
  if (existing && existing.approvalStatus !== "rejected") {
    // Already has a pending or approved code — skip
    return existing;
  }

  const code = await repo.createTrackingCode(blId, customerId, {
    expiresInDays: 365,
    autoGenerated: true,
    approvalStatus: "pending",
  });

  secureLogger.info(
    `[Tracking Service] Auto-generated tracking code ${code.code} (pending) for BL ${bl.blNumber} / Customer ${customer.fullName}`
  );

  // Notify owner about pending approval (fire-and-forget)
  notifyPendingApproval({
    blNumber: bl.blNumber,
    trackingCode: code.code,
    customerName: customer.fullName,
    vehicleDescription: bl.vehicleDescription,
    autoGenerated: true,
  }).catch((err) => console.error("[Tracking Service] Auto-gen notification error:", err));

  return code;
}

/**
 * Approve a pending tracking code — activates it and triggers notifications.
 */
export async function approveCode(
  id: number,
  adminUserId: number
): Promise<repo.TrackingCodeRecord> {
  const code = await repo.findTrackingCodeById(id);
  if (!code) throw new Error("Código de tracking não encontrado.");
  if (code.approvalStatus !== "pending") {
    throw new Error(`Código já está ${code.approvalStatus === "approved" ? "aprovado" : "rejeitado"}.`);
  }

  const approved = await repo.approveTrackingCode(id, adminUserId);
  if (!approved) throw new Error("Erro ao aprovar código.");

  await logAudit({
    userId: adminUserId,
    action: "update",
    entity: "tracking_code",
    entityId: id,
    changes: {
      approvalStatus: { before: "pending", after: "approved" },
      isActive: { before: false, after: true },
    },
  });

  // Get BL and customer for notifications
  const bl = await blRepo.findBlById(code.blId);
  const customer = await customerRepo.findCustomerById(code.customerId);

  if (bl && customer) {
    // Notify owner + prepare email/WhatsApp for customer (fire-and-forget)
    notifyCodeApproved({
      blNumber: bl.blNumber,
      trackingCode: code.code,
      customerName: customer.fullName,
      customerEmail: customer.email,
      customerPhone: customer.phone,
      customerId: customer.id,
      vehicleDescription: bl.vehicleDescription,
    }).catch((err) => console.error("[Tracking Service] Approval notification error:", err));
  }

  return approved;
}

/**
 * Reject a pending tracking code with optional reason.
 */
export async function rejectCode(
  id: number,
  reason?: string,
  adminUserId?: number
): Promise<repo.TrackingCodeRecord> {
  const code = await repo.findTrackingCodeById(id);
  if (!code) throw new Error("Código de tracking não encontrado.");
  if (code.approvalStatus !== "pending") {
    throw new Error(`Código já está ${code.approvalStatus === "approved" ? "aprovado" : "rejeitado"}.`);
  }

  const rejected = await repo.rejectTrackingCode(id, reason);
  if (!rejected) throw new Error("Erro ao rejeitar código.");

  await logAudit({
    userId: adminUserId ?? null,
    action: "update",
    entity: "tracking_code",
    entityId: id,
    changes: {
      approvalStatus: { before: "pending", after: "rejected" },
      rejectionReason: { before: null, after: reason ?? null },
    },
  });

  return rejected;
}

/**
 * Get pending codes count (for badge in admin UI).
 */
export async function countPendingCodes(): Promise<number> {
  return repo.countPendingCodes();
}

/**
 * List pending codes (for admin approval queue).
 */
export async function listPendingCodes(): Promise<repo.TrackingCodeRecord[]> {
  return repo.findPendingCodes();
}

/**
 * Get preview of email/WhatsApp messages that would be sent on approval.
 * Used by admin to review before approving.
 */
export async function getApprovalPreview(
  id: number
): Promise<{
  trackingCode: string;
  customerName: string;
  customerEmail: string | null;
  customerPhone: string | null;
  blNumber: string;
  vehicleDescription: string | null;
  emailTemplate: string | null;
  whatsAppTemplate: string | null;
}> {
  const code = await repo.findTrackingCodeById(id);
  if (!code) throw new Error("Código de tracking não encontrado.");

  const bl = await blRepo.findBlById(code.blId);
  const customer = await customerRepo.findCustomerById(code.customerId);
  if (!bl || !customer) throw new Error("BL ou cliente não encontrado.");

  const firstName = customer.fullName.split(" ")[0];

  // Build email template
  let emailTemplate: string | null = null;
  if (customer.email) {
    emailTemplate = [
      `Assunto: \ud83d\udd11 Seu C\u00f3digo de Rastreamento \u2014 EMC`,
      "",
      `Ol\u00e1, ${firstName}!`,
      "",
      "Temos boas not\u00edcias! Seu c\u00f3digo de rastreamento est\u00e1 pronto.",
      "Com ele, voc\u00ea pode acompanhar seu envio em tempo real.",
      "",
      `\ud83d\udce6 C\u00f3digo de Rastreamento: ${code.code}`,
      `\ud83d\udccb BL: ${bl.blNumber}`,
      bl.vehicleDescription ? `\ud83d\ude97 Ve\u00edculo: ${bl.vehicleDescription}` : "",
      "",
      "Como rastrear:",
      "1. Acesse https://enviandomeucarro.com/rastrear",
      `2. Insira o c\u00f3digo: ${code.code}`,
      "3. Acompanhe cada etapa do seu envio",
      "",
      "Qualquer d\u00favida, estamos \u00e0 disposi\u00e7\u00e3o!",
      "",
      "Atenciosamente,",
      "Equipe EMC \u2014 Enviando Meu Carro",
    ].filter(Boolean).join("\n");
  }

  // Build WhatsApp template
  let whatsAppTemplate: string | null = null;
  if (customer.phone) {
    whatsAppTemplate = [
      "\ud83d\udd11 *EMC \u2014 Seu C\u00f3digo de Rastreamento*",
      "",
      `Ol\u00e1, ${firstName}!`,
      "",
      "Seu c\u00f3digo de rastreamento est\u00e1 pronto:",
      `*${code.code}*`,
      "",
      bl.vehicleDescription ? `Ve\u00edculo: ${bl.vehicleDescription}` : "",
      `BL: ${bl.blNumber}`,
      "",
      "Acompanhe seu envio em tempo real:",
      "\ud83d\udd17 https://enviandomeucarro.com/rastrear",
      "",
      "_EMC \u2014 Enviando Meu Carro_",
    ].filter(Boolean).join("\n");
  }

  return {
    trackingCode: code.code,
    customerName: customer.fullName,
    customerEmail: customer.email,
    customerPhone: customer.phone,
    blNumber: bl.blNumber,
    vehicleDescription: bl.vehicleDescription,
    emailTemplate,
    whatsAppTemplate,
  };
}

// ── Deactivate a tracking code ───────────────────────────────
export async function deactivateCode(
  id: number,
  adminUserId?: number
): Promise<void> {
  const code = await repo.findTrackingCodeById(id);
  if (!code) throw new Error("Código de tracking não encontrado.");

  await repo.deactivateTrackingCode(id);

  await logAudit({
    userId: adminUserId ?? null,
    action: "update",
    entity: "tracking_code",
    entityId: id,
    changes: { isActive: { before: true, after: false } },
  });
}

// ── Reactivate a tracking code ───────────────────────────────
export async function reactivateCode(
  id: number,
  adminUserId?: number
): Promise<void> {
  await repo.reactivateTrackingCode(id);

  await logAudit({
    userId: adminUserId ?? null,
    action: "update",
    entity: "tracking_code",
    entityId: id,
    changes: { isActive: { before: false, after: true } },
  });
}

// ── List tracking codes ──────────────────────────────────────
export async function listTrackingCodes(
  query: PaginatedQuery & { approvalStatus?: repo.ApprovalStatus }
): Promise<PaginatedResult<repo.TrackingCodeRecord>> {
  return repo.listTrackingCodes(query);
}

// ── Get codes for a BL ───────────────────────────────────────
export async function getCodesForBl(
  blId: number
): Promise<repo.TrackingCodeRecord[]> {
  return repo.findActiveCodesByBlId(blId);
}

// ── Count active codes ───────────────────────────────────────
export async function countActiveCodes(): Promise<number> {
  return repo.countActiveCodes();
}

// ══════════════════════════════════════════════════════════════
// PUBLIC TRACKING LOOKUP
// ══════════════════════════════════════════════════════════════

// ── Lookup by tracking code (public endpoint) ────────────────
export async function lookupByCode(
  code: string
): Promise<PublicTrackingResult | null> {
  // Check cache first
  const cached = trackingCache.get(code.toUpperCase());
  if (cached) return cached;

  // Find the tracking code
  const trackingCode = await repo.findTrackingCodeByCode(code);
  if (!trackingCode) return null;

  // Check if active, approved, and not expired
  if (!trackingCode.isActive) return null;
  if (trackingCode.approvalStatus !== "approved") return null;
  if (trackingCode.expiresAt < new Date()) return null;

  // Increment usage counter (fire-and-forget)
  repo.incrementUsage(trackingCode.id).catch(() => {});

  // Get BL details
  const bl = await blRepo.findBlById(trackingCode.blId);
  if (!bl) return null;

  // Get tracking history
  const history = await repo.getTrackingHistory(trackingCode.blId);

  // Get linked vehicles via bl_vehicles junction (safe: no personal data)
  const blVehicleLinks = await blRepo.getVehiclesForBl(trackingCode.blId);
  const vehicleInfos: PublicVehicleInfo[] = [];
  for (const link of blVehicleLinks) {
    const vehicle = await vehicleRepo.findVehicleById(link.vehicleId);
    if (vehicle) {
      vehicleInfos.push({
        make: vehicle.make,
        model: vehicle.model,
        year: vehicle.year,
        color: vehicle.color,
      });
    }
  }

  const result: PublicTrackingResult = {
    code: trackingCode.code,
    blNumber: bl.blNumber,
    containerNumber: bl.containerNumber,
    originPort: bl.originPort,
    destinationPort: bl.destinationPort,
    vehicleDescription: bl.vehicleDescription,
    vehicles: vehicleInfos,
    status: bl.status,
    estimatedDeparture: bl.estimatedDeparture,
    actualDeparture: bl.actualDeparture,
    estimatedArrival: bl.estimatedArrival,
    actualArrival: bl.actualArrival,
    timeline: history.map((h) => ({
      status: h.status,
      location: h.location,
      description: h.description,
      eventDate: h.eventDate,
    })),
    lastUpdate: history.length > 0 ? history[0].eventDate : null,
  };

  // Cache for 5 minutes
  trackingCache.set(code.toUpperCase(), result);

  return result;
}

// ── Lookup by CPF (public endpoint) ──────────────────────────
export async function lookupByCpf(cpf: string): Promise<CpfLookupResult | null> {
  // Find customer by CPF hash
  const customer = await customerRepo.findCustomerByCpf(cpf);
  if (!customer) return null;

  // Get active tracking codes for this customer
  const codes = await repo.findActiveCodesByCustomerId(customer.id);
  if (codes.length === 0) return null;

  // Get BL details for each code
  const codeResults = await Promise.all(
    codes.map(async (tc) => {
      const bl = await blRepo.findBlById(tc.blId);
      return {
        codeMasked: maskCode(tc.code),
        blNumber: bl?.blNumber ?? "N/A",
        status: bl?.status ?? "unknown",
        vehicleDescription: bl?.vehicleDescription ?? null,
      };
    })
  );

  return {
    codes: codeResults,
    customerNameMasked: maskName(customer.fullName),
  };
}

// ══════════════════════════════════════════════════════════════
// TRACKING HISTORY
// ══════════════════════════════════════════════════════════════

// ── Add a tracking event ─────────────────────────────────────
export async function addTrackingEvent(
  data: {
    blId: number;
    status: string;
    location?: string;
    description?: string;
    eventDate?: Date;
    rawData?: string;
  },
  adminUserId?: number
): Promise<repo.TrackingHistoryRecord> {
  // Validate BL exists
  const bl = await blRepo.findBlById(data.blId);
  if (!bl) throw new Error("BL não encontrado.");

  const event = await repo.addTrackingEvent(data);

  // Invalidate cache for all codes linked to this BL
  const codes = await repo.findActiveCodesByBlId(data.blId);
  codes.forEach((c) => trackingCache.delete(c.code));

  await logAudit({
    userId: adminUserId ?? null,
    action: "create",
    entity: "tracking_event",
    entityId: event.id,
    changes: {
      created: { before: null, after: data.status },
      blId: { before: null, after: data.blId },
    },
  });

  // Dispatch notifications (fire-and-forget)
  dispatchEventNotifications({
    blId: data.blId,
    blNumber: bl.blNumber,
    eventType: data.status,
    title: data.description ?? data.status,
    description: data.description,
    location: data.location,
    eventDate: data.eventDate ?? new Date(),
    vehicleDescription: bl.vehicleDescription,
    customerId: bl.customerId ?? undefined,
  }).catch((err) => console.error("[Tracking Service] Notification dispatch error:", err));

  return event;
}

// ── Get tracking history for a BL ────────────────────────────
export async function getTrackingHistory(
  blId: number
): Promise<repo.TrackingHistoryRecord[]> {
  return repo.getTrackingHistory(blId);
}

// ── Delete a tracking event ──────────────────────────────────
export async function deleteTrackingEvent(
  id: number,
  adminUserId?: number
): Promise<void> {
  await repo.deleteTrackingEvent(id);

  await logAudit({
    userId: adminUserId ?? null,
    action: "delete",
    entity: "tracking_event",
    entityId: id,
    changes: { deleted: { before: false, after: true } },
  });
}

// ══════════════════════════════════════════════════════════════
// HELPERS
// ══════════════════════════════════════════════════════════════

/** Mask a tracking code: EMC-AB3D-****-**** */
function maskCode(code: string): string {
  const parts = code.split("-");
  if (parts.length !== 4) return code;
  return `${parts[0]}-${parts[1]}-****-****`;
}

/** Mask a name: "João Silva" → "João S***" */
function maskName(name: string): string {
  const parts = name.trim().split(" ");
  if (parts.length <= 1) return name.charAt(0) + "***";
  const first = parts[0];
  const lastInitial = parts[parts.length - 1].charAt(0);
  return `${first} ${lastInitial}***`;
}
